repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0 # use the latest Ruff version
    hooks:
      - id: ruff-format
        stages: [pre-commit]   # run at commit time
        pass_filenames: true
        always_run: true
