x-base: &base
  image: medicareai
  build: .
  restart: unless-stopped
  env_file: 
    - .env

services:
  cli:
    <<: *base
    command: python -m src.cli
  telegram-bot:
    <<: *base
    command: python -m src.tg_bot
  email_service:
    <<: *base
    command: python -m src.services.email.email_service
  api:
    <<: *base
    ports: 
      - "8000:8000"
    command: uvicorn src.api.main:app --host 127.0.0.1 --port 8000
